# Internal routing configuration to handle ESI
# ****** WARNING ******
# This route should be enabled with caution as it can open a security vulnerability
# see http://symfony.com/blog/security-release-symfony-2-0-20-and-2-1-5-released for more information
# ****** WARNING ******
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
foo:
    pattern:   /welcome
    defaults: {_controller: AcmeDemoBundle:Welcome:foo}
new:
    pattern:   /new
    defaults: {_controller: AcmeDemoBundle:Welcome:new}	
show:
    pattern:   /show
    defaults: {_controller: AcmeDemoBundle:Welcome:show}	